name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Debug environment
        run: |
          echo "Current working directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
          echo "Network connectivity test:"
          ping -c 3 10.14.120.26 || echo "Ping failed"
          
      - name: Test SonarQube connectivity
        run: |
          echo "Testing SonarQube server status..."
          curl -f ${{ secrets.SONAR_HOST_URL }}/api/system/status || echo "Server status check failed"
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
