name: Shell & CSV Analyzer CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  shell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Shell Scripts
      run: |
        chmod +x scripts/*.sh
        ./scripts/clean_csv.sh sample.csv || echo "Sample not found"
        ./scripts/generate_report.sh sample.csv || echo "Sample not found"
